server:
  port: 8090
logging:
  level:
    io.github.resilience4j: DEBUG
spring:
  application:
    name: seguros-banco
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5433/seguros_banco
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  doc:
    api-docs:
      path: /api-docs
      enabled: true
      swagger-ui-path: /swagger-ui
      operations-sorter: method
      tags-sorter: alpha
      disable-swagger-default-url: false
resilience4j:
  circuitbreaker:
    instances:
      myService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
  retry:
    instances:
      myService:
        max-attempts: 3
        wait-duration: 2s
  ratelimiter:
    instances:
      myService:
        limit-for-period: 5
        limit-refresh-period: 10s
        timeout-duration: 1s
management:
  endpoints:
    web:
      exposure:
        include: resilience4j-circuitbreaker, health
  health:
    circuitbreakers:
      enabled: true